resource_group_name           = "myapp-grp"
resources_location            = "East US"
virtual_network_name          = "myvnet"
virtual_network_address_space = ["10.10.0.0/16"]
subnet_prefix                 = ["10.10.0.0/24"]
loadBalancerSKU               = "Standard"
public_ip_name                = "test-public-ip"
admin_username                = "hbhargava"
admin_password                = "TestPassword@123456"
